# Generated by Django 5.2 on 2025-05-15 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'admin user', 'verbose_name_plural': 'admin users'},
        ),
    ]
