# Generated by Django 4.2.20 on 2025-05-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jobseekercv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekercv',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='employment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='family',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='scholarships',
            field=models.TextField(blank=True, null=True),
        ),
    ]
