# Generated by Django 5.2 on 2025-05-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_jobseekercv_no_dependents'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
