# Generated by Django 5.2 on 2025-05-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_adminuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('aptitude', 'Aptitude'), ('technical', 'Technical'), ('personality', 'Personality')], max_length=100)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=50)),
                ('choices', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
