# Generated by Django 5.2 on 2025-05-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_adminuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_category', models.CharField(max_length=100)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=10)),
                ('question_text', models.TextField(blank=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('question_format', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('checkboxes', 'Checkboxes')], max_length=20)),
                ('has_answer_key', models.BooleanField(default=False)),
                ('answer_key', models.CharField(blank=True, max_length=255)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
