# Generated by Django 5.2 on 2025-05-26 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answer_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='has_answer_key',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='question_format',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True / False'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('checkboxes', 'Checkboxes')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('Image Pattern Analysis', 'Image Pattern Analysis'), ('Basic Math', 'Basic Math'), ('Problem Analysis and Solving', 'Problem Analysis and Solving'), ('Reading Comprehension', 'Reading Comprehension'), ('Pre Interview Questionnaire', 'Pre Interview Questionnaire'), ('Sentence Completion', 'Sentence Completion'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=20),
        ),
    ]
