# Generated by Django 5.2 on 2025-05-26 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_test_answer_key_test_created_at_test_has_answer_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_category', models.CharField(choices=[('Image Pattern Analysis', 'Image Pattern Analysis'), ('Basic Math', 'Basic Math'), ('Problem Analysis', 'Problem Analysis'), ('Reading Comprehension', 'Reading Comprehension'), ('Pre Interview Questionnaire', 'Pre Interview Questionnaire'), ('Sentence Completion', 'Sentence Completion'), ('Other', 'Other')], max_length=50)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=10)),
                ('question_text', models.TextField(blank=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('question_format', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True / False'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('checkboxes', 'Checkboxes')], max_length=20)),
                ('has_answer_key', models.BooleanField(default=False)),
                ('answer_key', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.question'),
        ),
    ]
