# Generated by Django 5.2 on 2025-05-19 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Admin User', 'verbose_name_plural': 'Admin Users'},
        ),
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exam Question', 'verbose_name_plural': 'Exam Questions'},
        ),
        migrations.AlterModelOptions(
            name='jobseekercv',
            options={'ordering': ['-date_applied'], 'verbose_name': 'Jobseeker CV', 'verbose_name_plural': 'Jobseeker CVs'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='hasAnswerKey',
            new_name='has_answer_key',
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='choices',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='education',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='employment',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='family',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='no_dependents',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='references',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='scholarships',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_format',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('checkboxes', 'Checkboxes')], max_length=30),
        ),
    ]
