# Generated by Django 5.2 on 2025-05-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_adminuser_options_alter_examquestion_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'admin user', 'verbose_name_plural': 'admin users'},
        ),
        migrations.AlterModelOptions(
            name='jobseekercv',
            options={},
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='employment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='family',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='no_dependents',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercv',
            name='scholarships',
            field=models.TextField(blank=True, null=True),
        ),
    ]
