# Generated by Django 5.2 on 2025-05-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_examquestion_delete_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_category', models.CharField(choices=[('Image Pattern Analysis', 'Image Pattern Analysis'), ('Basic Math', 'Basic Math'), ('Problem Analysis and Solving', 'Problem Analysis and Solving'), ('Reading Comprehension', 'Reading Comprehension'), ('Pre Interview Questionnaire', 'Pre Interview Questionnaire'), ('Sentence Completion', 'Sentence Completion'), ('Other', 'Other')], max_length=255)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=10)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('question_format', models.CharField(max_length=20)),
                ('has_answer_key', models.BooleanField(default=False)),
                ('answer_key', models.TextField(blank=True, null=True)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
