# Generated by Django 5.2 on 2025-05-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_testsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubmission',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='test_category',
            field=models.CharField(choices=[('Image Pattern Analysis', 'Image Pattern Analysis'), ('Basic Math', 'Basic Math'), ('Problem Analysis', 'Problem Analysis'), ('Reading Comprehension', 'Reading Comprehension'), ('Pre Interview Questionnaire', 'Pre Interview Questionnaire'), ('Sentence Completion', 'Sentence Completion'), ('Other', 'Other')], default=8, max_length=50),
            preserve_default=False,
        ),
    ]
